### ISSUE TITLE
Can the kernel5.15 work on Android 9?

### ISSUE THREAD

**Issue by iiowoii3389** [maurossi/linux#23] opened 2023-01-17 16:30 UTC
I used the kernel source code here(https://github.com/aosp-mirror/kernel_common/tree/android13-5.15-lts)Try to start the system on Android 9,But it doesn't work properly,After entering the system, his graphical interface does not refresh. It is stagnant. The kernel does not crash. There are many errors in logcat. I suspect this is a kernel problem,
[logcat.log](https://github.com/maurossi/linux/files/10437236/logcat.log)
[dmesg.log](https://github.com/maurossi/linux/files/10437238/dmesg.log)

So can the 5.15 branches of the Repository work on Android 9

**Comment by maurossi** [comment] 2023-01-18 09:33
Hello, your issue with AOSP kernel 5.15 LTS for Android 13 is unrelated with kernel-5.15 in this github repository

What you may try yourself is if using this repository kernel-5.15 works with your Android 9 build, but disclaimer warning this kernel-5.15 branch is minimal and experimental and not yet an official  public kernel branches in android-x86 repository.

`git fetch [this_repo] kernel-5.15`
`git checkout FETCH_HEAD`

After that first attempt, if you see that the problem is not present anymore, then you may move to try to apply the series of commits in kernel-5.15 which are on top of commit 8bb7eca972ad531c9b149c0a51ab43a417385813 "Linux 5.15" onto android13-5.15-lts HEAD

Since you have completed the build of android13-5.15-lts, you will not need to revert the patches that enforce the use of gcc 5.1 and you will not need the dce6 experimental patches

[checkout android13-5.15-lts]
`git fetch [this_repo] kernel-5.15`
`git cherry-pick 8bb7eca972ad531c9b149c0a51ab43a417385813..bc6e95ce05f3b0e4a0cee0a4267a17d335f4b6fb`

the you will have to resolve any conflicts that may arise.

Closing as off-topic, but as you have seen I have provided you instructions on how to proceed on your own

**Closed as completed by maurossi** 2023-01-18 09:33 UTC
